# Generated by Django 3.2.5 on 2021-07-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('high', models.CharField(max_length=50)),
                ('low', models.CharField(max_length=50)),
                ('close', models.BooleanField()),
                ('symbol', models.CharField(max_length=50)),
            ],
        ),
    ]
